//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meetings_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public string Place { get; set; }
        public string Topic { get; set; }
        public int PersonListId { get; set; }
    
        public virtual PersonList Person { get; set; }
    }
}
